import type { Metadata } from "next";
import Sidebar from "@/components/sidebar/Sidebar";



export const metadata: Metadata = {
    title: "Mini Ecommercy",
    description: "Generated by create next app",
};

// Define the RootLayout component which will be used as the main layout for the application
export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode; // Define the type for children prop
}>) {
    return (
        <>
            <Sidebar />
            {children} {/* Render the children components */}

        </>

    );
}
